// 5250ng - A modern IBM TN5250 terminal emulator
// Copyright (C) 2025-2026 Remi GASCOU (Podalirius)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include <QJsonArray>
#include <QJsonObject>
#include <QString>

namespace agent {

// ---------------------------------------------------------------------------
// run_5250script — execute a script on the terminal
// ---------------------------------------------------------------------------

inline const QString kToolRunScript = QStringLiteral("run_5250script");

inline const QString kToolRunScriptDescription = QStringLiteral(
    "Execute a 5250script on the current terminal session. "
    "The script interacts with the live AS/400 session. "
    "Use this to run scripts generated by generate_5250script.");

inline QJsonObject toolRunScriptSchema() {
    QJsonObject scriptProp;
    scriptProp["type"] = "string";
    scriptProp["description"] = "The 5250script source code to execute";

    QJsonObject properties;
    properties["script"] = scriptProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"script"};
    return schema;
}

// ---------------------------------------------------------------------------
// generate_5250script — generate a script via subagent
// ---------------------------------------------------------------------------

inline const QString kToolGenerateScript = QStringLiteral("generate_5250script");

inline const QString kToolGenerateScriptDescription = QStringLiteral(
    "Generate a 5250script from a natural language task description. "
    "A specialized subagent with full knowledge of the 5250script language "
    "will generate the script code. The generated script is returned as text "
    "which you can then pass to run_5250script to execute it. "
    "Use this for any terminal automation task.");

inline QJsonObject toolGenerateScriptSchema() {
    QJsonObject taskProp;
    taskProp["type"] = "string";
    taskProp["description"] =
        "Natural language description of the task the script should perform";

    QJsonObject properties;
    properties["task"] = taskProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"task"};
    return schema;
}

// ---------------------------------------------------------------------------
// Provider-specific tool array builders
// ---------------------------------------------------------------------------

inline QJsonArray anthropicToolsArray() {
    QJsonObject runTool;
    runTool["name"] = kToolRunScript;
    runTool["description"] = kToolRunScriptDescription;
    runTool["input_schema"] = toolRunScriptSchema();

    QJsonObject genTool;
    genTool["name"] = kToolGenerateScript;
    genTool["description"] = kToolGenerateScriptDescription;
    genTool["input_schema"] = toolGenerateScriptSchema();

    return QJsonArray{genTool, runTool};
}

inline QJsonArray openaiToolsArray() {
    QJsonObject runFunc;
    runFunc["name"] = kToolRunScript;
    runFunc["description"] = kToolRunScriptDescription;
    runFunc["parameters"] = toolRunScriptSchema();
    QJsonObject runTool;
    runTool["type"] = "function";
    runTool["function"] = runFunc;

    QJsonObject genFunc;
    genFunc["name"] = kToolGenerateScript;
    genFunc["description"] = kToolGenerateScriptDescription;
    genFunc["parameters"] = toolGenerateScriptSchema();
    QJsonObject genTool;
    genTool["type"] = "function";
    genTool["function"] = genFunc;

    return QJsonArray{genTool, runTool};
}

} // namespace agent
