// 5250ng - A modern IBM TN5250 terminal emulator
// Copyright (C) 2025-2026 Remi GASCOU (Podalirius)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include <QJsonArray>
#include <QJsonObject>
#include <QString>

namespace agent {

// ---------------------------------------------------------------------------
// run_5250script — execute a script on the terminal
// ---------------------------------------------------------------------------

inline const QString kToolRunScript = QStringLiteral("run_5250script");

inline const QString kToolRunScriptDescription = QStringLiteral(
    "Execute a 5250script on the current terminal session. "
    "The script interacts with the live AS/400 session. "
    "Use this to run scripts generated by generate_5250script.");

inline QJsonObject toolRunScriptSchema() {
    QJsonObject scriptProp;
    scriptProp["type"] = "string";
    scriptProp["description"] = "The 5250script source code to execute";

    QJsonObject properties;
    properties["script"] = scriptProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"script"};
    return schema;
}

// ---------------------------------------------------------------------------
// generate_5250script — generate a script via subagent
// ---------------------------------------------------------------------------

inline const QString kToolGenerateScript = QStringLiteral("generate_5250script");

inline const QString kToolGenerateScriptDescription = QStringLiteral(
    "Generate a 5250script from a natural language task description. "
    "A specialized subagent with full knowledge of the 5250script language "
    "will generate the script code. The generated script is returned as text "
    "which you can then pass to run_5250script to execute it. "
    "Use this for any terminal automation task.");

inline QJsonObject toolGenerateScriptSchema() {
    QJsonObject taskProp;
    taskProp["type"] = "string";
    taskProp["description"] =
        "Natural language description of the task the script should perform";

    QJsonObject properties;
    properties["task"] = taskProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"task"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_file — read a file from the local filesystem
// ---------------------------------------------------------------------------

inline const QString kToolReadFile = QStringLiteral("read_file");

inline const QString kToolReadFileDescription = QStringLiteral(
    "Read the contents of a file from the local filesystem. "
    "Returns the full text content of the file.");

inline QJsonObject toolReadFileSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The absolute or relative path to the file to read";

    QJsonObject properties;
    properties["path"] = pathProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"path"};
    return schema;
}

// ---------------------------------------------------------------------------
// write_file — write content to a file on the local filesystem
// ---------------------------------------------------------------------------

inline const QString kToolWriteFile = QStringLiteral("write_file");

inline const QString kToolWriteFileDescription = QStringLiteral(
    "Write content to a file on the local filesystem. "
    "Creates the file if it does not exist, or overwrites it if it does.");

inline QJsonObject toolWriteFileSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The absolute or relative path to the file to write";

    QJsonObject contentProp;
    contentProp["type"] = "string";
    contentProp["description"] = "The text content to write to the file";

    QJsonObject properties;
    properties["path"] = pathProp;
    properties["content"] = contentProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"path", "content"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_screen — read the current terminal screen content
// ---------------------------------------------------------------------------

inline const QString kToolReadScreen = QStringLiteral("read_screen");

inline const QString kToolReadScreenDescription = QStringLiteral(
    "Read the current content of the 5250 terminal screen. "
    "Returns the full text of all rows on the screen. "
    "Use this to see what is displayed after running a script or at any time.");

inline QJsonObject toolReadScreenSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// list_files — list files and directories
// ---------------------------------------------------------------------------

inline const QString kToolListFiles = QStringLiteral("list_files");

inline const QString kToolListFilesDescription = QStringLiteral(
    "List files and directories at a given path on the local filesystem. "
    "Returns names, types (file or directory), and sizes.");

inline QJsonObject toolListFilesSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The directory path to list. Defaults to current directory if empty.";

    QJsonObject properties;
    properties["path"] = pathProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    return schema;
}

// ---------------------------------------------------------------------------
// send_keys — send keystrokes to the terminal
// ---------------------------------------------------------------------------

inline const QString kToolSendKeys = QStringLiteral("send_keys");

inline const QString kToolSendKeysDescription = QStringLiteral(
    "Send one or more keystrokes to the terminal session. "
    "Accepts a space-separated list of key names. "
    "Supported keys: Enter, F1-F24, Tab, Backspace, PageUp, PageDown, "
    "Home, End, Insert, Delete, Escape, Up, Down, Left, Right, FieldExit. "
    "Text can be typed by wrapping in quotes, e.g. send_keys with keys='\"hello\" Enter'. "
    "This is lighter weight than run_5250script for simple key presses.");

inline QJsonObject toolSendKeysSchema() {
    QJsonObject keysProp;
    keysProp["type"] = "string";
    keysProp["description"] =
        "Space-separated key names to send, e.g. 'F3' or 'Tab \"mytext\" Enter'";

    QJsonObject properties;
    properties["keys"] = keysProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"keys"};
    return schema;
}

// ---------------------------------------------------------------------------
// get_cursor_position — get the current cursor position
// ---------------------------------------------------------------------------

inline const QString kToolGetCursorPosition = QStringLiteral("get_cursor_position");

inline const QString kToolGetCursorPositionDescription = QStringLiteral(
    "Get the current cursor position on the terminal screen. "
    "Returns the row and column (0-based) of the cursor.");

inline QJsonObject toolGetCursorPositionSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// get_field_at — get field information at a screen position
// ---------------------------------------------------------------------------

inline const QString kToolGetFieldAt = QStringLiteral("get_field_at");

inline const QString kToolGetFieldAtDescription = QStringLiteral(
    "Get information about the input field at a given screen position. "
    "Returns the field's start position, length, whether it is protected (read-only), "
    "and its current text content. Returns an error if no field exists at the position.");

inline QJsonObject toolGetFieldAtSchema() {
    QJsonObject rowProp;
    rowProp["type"] = "integer";
    rowProp["description"] = "Row on the screen (0-based)";

    QJsonObject colProp;
    colProp["type"] = "integer";
    colProp["description"] = "Column on the screen (0-based)";

    QJsonObject properties;
    properties["row"] = rowProp;
    properties["col"] = colProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"row", "col"};
    return schema;
}

// ---------------------------------------------------------------------------
// Provider-specific tool array builders (defined in tool_definitions.cpp)
// ---------------------------------------------------------------------------

QJsonArray anthropicToolsArray();
QJsonArray openaiToolsArray();

} // namespace agent
